version: '3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    networks:
      - node-network
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    command: node index.js
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - /mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

