FROM nginx:1.15.0-alpine

# substituir arquivo de configuracao pelo nosso arquivo
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# criar um arquivo para o funcionamento do nginx, se nao criar toma 404
RUN mkdir /var/www/html -p && touch /var/www/html/index.js
